# A basic redirect rule
[[redirects]]
  from = "/*"
  to = "/ua/:splat"
  status = 302
  force = true
  conditions = {Country = ["UA"]}

[[redirects]]
  from = "/"
  to = "/us/"
  status = 302
  force = true
  conditions = {Country = ["US"]}
  
[[redirects]]
  from = "/*"
  to = "/us/:splat"
  status = 302
  force = true
  conditions = {Country = ["US"]}


