backend:
  name: git-gateway
  branch: main

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Layout, name: layout, widget: hidden, default: blog }
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: Body, name: body, widget: markdown, required: false }
      - { label: image, name: featuredimage, widget: image }
      - {
          label: "Author",
          name: "author",
          widget: "relation",
          collection: "authors",
          value_field: "email",
          search_fields: ["name", "email"],
          display_fields: ["name"],
        }
  - name: authors
    label: Authors
    folder: content/blog/_authors/
    format: json
    create: true
    slug: "{{name}}"
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Email, name: email, widget: string }
      - { label: Image, name: authorimage, widget: image }

  - name: podcast
    label: Podcast
    folder: content/podcast
    format: json
    create: true
    slug: "{{title}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime }
      - { label: AudioLink, name: audio, widget: string }
      - { label: Image, name: podcastImage, widget: image }

  - name: team
    label: Team
    folder: content/team
    format: json
    create: true
    slug: "{{name}}"
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Title, name: title, widget: string }
      - {
          label: Order,
          name: order,
          widget: number,
          value_type: int,
          min: 1,
          default: null,
          required: false,
        }
      - { label: LinkedIn, name: linkedin, widget: string, required: false }
      - { label: Image, name: image, widget: image }

  - name: partners
    label: Partners
    folder: content/partners
    create: true
    widget: object
    fields:
      - { name: path, label: Path }
      - name: sectionFAQ
        label: Section FAQ
        widget: object
        requried: false
        fields:
          - { name: title, label: Title, widget: string }
          - {
              name: content,
              label: Content,
              required: false,
              widget: list,
              fields:
                [
                  { name: question, label: Question, widget: string },
                  { name: body, label: Body, widget: markdown },
                ],
            }
